/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToPythonConverter */

#ifndef _Included_JavaToPythonConverter
#define _Included_JavaToPythonConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToPythonConverter
 * Method:    convertJavaToPython
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaToPythonConverter_convertJavaToPython
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
